name: workflow2

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: print job name
      run: echo "Job name $GITHUB_JOB"
  
  job2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: print job name
      run: echo "Job name $GITHUB_JOB"

