name: workflow3

on:
  push:
    branches:
      - main
      
jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    outputs:
      username: ${{ steps.step1.outputs.test }}
    steps:
    - name: passvalue
      id: step1
      run: |
        echo "job1 pass value"
        echo "::set-output name=outputs.test::halah"
  
  job2:
    runs-on: ubuntu-latest
    needs: 
      - job1
    steps:
    - name: print passed value
      run: echo "job2 catch the value > ${{ needs.job1.outputs.test }}"


