name: workflow3

on:
  push:
    branches:
      - main
      
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
    steps:
    - id: step1
      run: |
        echo "job1 pass value"
        echo "test=halah" >> "$GITHUB_OUTPUT"
  
  job2:
    runs-on: ubuntu-latest
    needs: 
      - job1
    steps:
    - env:
        OUTPUT1: ${{needs.job1.outputs.output1}}
    - name: print passed value
      run: echo "job2 catch the value > $OUTPUT1"


