name: workflow3

on:
  push:
    branches:
      - main
      

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      username: ${{ steps.print-job-name.outputs.username }}
    steps:
    steps:
    - uses: actions/checkout@v2
    - name: pass value
      run: |
      echo "job1 pass value"
      echo "::set-output name=username::halah"
  
  job2:
    runs-on: ubuntu-latest
    needs: 
      - job1
    steps:
    - uses: actions/checkout@v2
    - name: print passed value
      run: echo "job2 catch the value > $USERNAME"